### ISSUE TITLE
ESPHome 2026.2.1 fatal error: WiFiUdp.h: No such file or directory

### ISSUE THREAD

**Issue by dstigsson** [RobertJN64/ESPHome-NTP-Server#15]
Hi,
Thanks for this component.

After latest ESPHome update (2026.2.1) I get this error messages then installing to ESP32 board.
This worked fine in provies ESPHome versions (2026.1)

If you need any mote information or testing please revert back and i'm happy to help.

**Error messages:**
src/esphome/components/ntp_server/ntp_server.cpp:3:10: fatal error: WiFiUdp.h: No such file or directory

**Install Log:**
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-arduinoespressif32 @ 3.3.7 
 - framework-arduinoespressif32-libs @ 5.5.2 
 - framework-espidf @ 3.50502.0 (5.5.2) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.2 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.10
Compiling .pioenvs/ntp/src/esphome/components/api/api_connection.cpp.o
...
Compiling .pioenvs/ntp/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/ntp/src/esphome/components/ntp_server/ntp_server.cpp.o
**src/esphome/components/ntp_server/ntp_server.cpp:3:10: fatal error: WiFiUdp.h: No such file or directory**

***********************************************************************
* Looking for WiFiUdp.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFiUdp.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKWiFiUdp.h
*
***********************************************************************

    3 | #include <WiFiUdp.h>
      |          ^~~~~~~~~~~
compilation terminated.
*** [.pioenvs/ntp/src/esphome/components/ntp_server/ntp_server.cpp.o] Error 1
========================= [FAILED] Took 52.50 seconds =========================

**Comment by RobertJN64** [comment]
Thanks for the report, I will try to reproduce tonight. The WiFiUdp library should be included as part of arduino-esp32, so not sure why it wouldn't be available.

**Comment by RobertJN64** [comment]
Was able to reproduce - looks like this is the issue: https://developers.esphome.io/blog/2026/02/12/esp32-arduino-selective-compilation-libraries-disabled-by-default/

**Comment by RobertJN64** [comment]
Fixed: https://github.com/RobertJN64/ESPHome-NTP-Server/commit/2c05c7b8ce09f76c0edfa4ab8cf203188ac1bab2

Feel free to re-open if you run into any other issues, but this fixed things on my end.
